
volumes:
  ## For making sure the ./docker dir is not bound recursively.
  dockerdirectory:

services:
  db:
    ## For Apple silicon. Change to linux/amd64 or linux/x86_64 as needed.
    platform: linux/arm64/v8

    ## Same as core as of WP 6.9.
    image: mysql:8.0

    container_name: cs_forms_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    env_file:
      - default.env
      - .env

  wordpress:
    container_name: cs_forms_wordpress
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: cs_forms_wordpress:localbuild
    volumes:
      - ..:/var/www/html/wp-content/plugins/crowdsignal-forms
      ## Kludge for not having docker contain recursive stuff
      ## You will see on your filesystem that this dir gets created
      - dockerdirectory:/var/www/html/wp-content/plugins/crowdsignal-forms/docker
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./wordpress-develop:/tmp/wordpress-develop
      - ./wordpress:/var/www/html
      - ./logs/apache2/:/var/log/apache2
      - ./logs/php:/var/log/php
      - ./bin:/var/scripts
      - ../../crowdsignal-plugin:/var/www/html/wp-content/plugins/polldaddy
    ports:
      - "${PORT_CS_WORDPRESS:-8000}:80"
    restart: always
    extra_hosts:
      - "api.crowdsignal.com:${CS_SANDBOX_IP:-192.0.123.248}"
      - "app.crowdsignal.com:${CS_SANDBOX_IP:-192.0.123.248}"
      - "api.polldaddy.com:${CS_SANDBOX_IP:-192.0.123.248}"
    env_file:
      - default.env
      - .env
